server: { port: 8088 }
spring:
  application: { name: fx-risk-gateway }
  datasource:
    url: jdbc:mysql://localhost:3306/risk?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root
